### ISSUE TITLE
Categorize jumpy functions

### ISSUE THREAD

**Issue by bheijden** [Farama-Foundation/Jumpy#28]
It seems there are more-or-less two types of functions. 
1. Functions that construct new arrays. (e.g. jp.array, jp.ones, jp.eye).
2. Functions that take arrays as input, manipulate them, and output the result (e.g. jp.matmul).

Functions in category 1 are affected by the global switch, in contrast to the functions in category 2. Category 2 functions decide on their implementation based on the array types (numpy, jax, builtin-in) of its inputs. Making this split explicit may make implementing a call order later on easier?

It might be worth splitting jumpy into three files: custom functions, category 1 and category 2 functions

This will make it easier to test as the functions in each file should operate in a "similar" way.

**Comment by pseudo-rnd-thoughts** [comment]
Done in #30
